seed: 0
# 200 RPM / 60 = 3.33, round to 4 seconds per req
delay: 4
model: gpt-4-vision-preview
max_tokens: 1024
temperature: 1.0
top_p: 0.7
system_prompt: >
  You are a helpful linguistic assistant.
  Explain why this answer is correct in great detail, referencing the provided image. Think step-by-step, and make sure to only draw conclusions from evidence present in the provided image.
